---
version: "> 0.17.0"

header-from: "_header.md"
footer-from: "_footer.md"

# see: https://terraform-docs.io/user-guide/configuration/#formatters
formatter: markdown table

# see: https://terraform-docs.io/user-guide/configuration/#sections
sections:
  show:
    - header
    - inputs
    - outputs
    - providers
    - modules
    - footer
    - resources
    - requirements

content: |-
  {{ .Header }}
  {{ .Footer }}

output:
  file: README.md
  mode: replace
  template: |-
    {{ .Content }}


sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  required: true
  type: true
  sensitive: true